source 'https://rubygems.org'

gem 'concurrent-ruby', '~> 1.1.5'
gem 'activesupport', '~> 5.2.3'
gem 'pry', '~> 0.12.2'
gem 'rack', '~> 2.0.7'
gem 'rake', '~> 12.3.2'
gem 'sqlite3', '~> 1.4.0'
gem 'i18n', '~> 1.6.0'
