#!/bin/bash
set -ex
XCODEPATH=`xcode-select -p`
if [[ ! -e "$XCODEPATH/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk" ]]; then
	echo " *** ERROR: the OS X ${MACOSX_DEPLOYMENT_TARGET} SDK is required. Please refer to" \
		"https://github.com/phusion/traveling-ruby/blob/master/osx/README.md" \
		"for installation instructions." >&2
	exit 1
fi
